### PR TITLE
Header overlaps side panel

### LINKED ISSUE #157: Header overlaps side panel
### Currently
* Header overlaps slightly with side panel (orange)
* Space in top header not maximised (green)

CCI___Data_Curator

### Description (acceptance criteria)
- [ ] Remove overlap (push sidepanel down to fit in header) (orange)
- [ ] If possible, make use of maximum header width (green)

### Why (hypothesis)
* Aesthetic

### PR DESCRIPTION
**Pull request by pegnott**
Fixes #157

### CODE REVIEW

**Comment by pegnott** [comment]
image

**Comment by AJamesPhillips** [comment]
This is looking great!!

I don't know how easy it is to do, and perhaps it will mess up the canvas movement and positioning but it looks like the main content is not being moved down when the header size increases.  i.e. this is what it should look like:

image

And then when the header is thicker it looks like this (orange shows where there's less distance above header than before):

CCI___Data_Curator

As this is really not a big issue i.e. a user would have to have a lot of nested knowledge views to get 3 rows of breadcrumb and obscure the items on the side panel / other views, I think we can safely leave this and merge as is but if you want to try to fix it and it doesn't mess with the canvas coordinates for moving nodes then let's do that.  I'll leave it with you to decide what's best / possible-excluding-significant-rewrite.

**Comment by pegnott** [comment]
image

**Comment by AJamesPhillips** [comment]
This looks **great**!

**Pull request merged**
