### PR TITLE
Pegnott/issue134 / collapsible side panel

### PR DESCRIPTION
**Pull request by pegnott**

### CODE REVIEW

**Comment by AJamesPhillips** [comment]
This is looking great.  Would it be possible to move the cross over to where the menu icon currently is and always keep the menu item in the top right?

**Comment by AJamesPhillips** [comment]
This is looking great. Would it be possible to move the cross over to where the menu icon currently is and always keep the menu item in the top right please?

**Comment by pegnott** [comment]
Yep, can do. Will get implemented this afternoon.

**Comment by pegnott** [comment]
https://user-images.githubusercontent.com/11094740/133138871-5289dc0a-77d4-469b-b4eb-588169e44111.mov

**Pull request merged**
